export default function Home() {
  return (
    <main className="academic-page">
      <header className="page-header">
        <h1>Paula Agustina López Villalba</h1>
      </header>
      <div className="profile-layout">
      <aside className="profile" aria-label="Photo and contact">
        <img className="profile-photo" src="/foto.jpg" alt="Paula Agustina López Villalba" width={200} height={200} />
        <p className="profile-links">
          <a href="/CV-Lopez.pdf" target="_blank" rel="noopener noreferrer">CV</a>
          {" | "}<strong>Email:</strong>{" "}
          <a href="mailto:plopezv@umich.edu">plopezv@umich.edu</a>
        </p>
      </aside>
      <div className="academic-content">
      <section className="introduction" aria-label="About me">
        <p>
          Welcome to my website! I&apos;m a Ph.D. candidate in Economics at the
          University of Michigan.
        </p>
        <p>
          My research interests are in Labor Economics, Family Economics, and
          Economic Development, with a particular interest in how institutions
          and public policies shape labor supply and household behavior.
        </p>
      </section>
      <section className="research-section" aria-labelledby="working-papers">
        <h2 id="working-papers">Working Papers</h2>
        <article className="publication">
          <h3>Child Support and Labor Supply in a High-Informality Setting</h3>
          <p><a href="https://www.dropbox.com/scl/fi/uw3zq37832szkgqyddrv6/latest.pdf?rlkey=68100p4gv3djhjdtaw86jbsvv&st=mcfdpbjj&dl=0">[Latest version]</a></p>
          <p><em>Job Market Paper</em></p>
          <p className="meta">with <a href="https://www.rosariod.com/">Rosario Didier</a></p>
          <p className="meta">Presented at: MDev 2026 Conference, Workshop on Gender and Household Inequality CAF-WELAC 2025, NTA Annual Conference 2025</p>
          <details className="abstract">
            <summary>Abstract</summary>
            <p>
              We study how mothers and fathers adjust their labor supply following family separation in a setting with widespread labor informality. We build a new dataset by combining child-support and family-court records from Ecuador and then link it to administrative records. Relative to observationally similar parents who remain in stable households, fathers&apos; formal employment declines by 5% in the year following separation, while mothers&apos; formal employment increases by 6%. Because family separation combines household dissolution with the onset of child-support obligations, we unpack this bundle in two ways. First, we use individuals who also experience household dissolution but do not have dependent children as an alternative control group. Second, we study parents who enter the child-support system following a first birth outside a shared household, so that child support begins without contemporaneous household dissolution. Together, the results point to child support as an important factor behind fathers&apos; decline in formal employment. We then show that much of this decline is accounted for by a shift toward informal employment. We examine whether the child-support system can contribute to this response and find that fathers who remain formally employed through the hearing face 20% higher obligations, conditional on pre-filing formal labor income. We estimate a model of household labor supply, fertility, and divorce and show that child-support incentives can induce formal-to-informal switching.
            </p>
          </details>
        </article>
        <article className="publication">
          <h3>The Effects of Coca Cultivation on Peruvian Local Economic Development</h3>
          <p>[Latest version]</p>
          <p className="meta">with <a href="https://jendara.com/">Joaquin Endara Cevallos</a></p>
          <details className="abstract">
            <summary>Abstract</summary>
            <p>
              This paper studies the effects of coca cultivation on local development in Peru between 2004 and 2017. To address endogeneity, we exploit plausibly exogenous variation in coca exposure generated by the interaction of local coca suitability with lagged coca production in Colombia and Bolivia. We combine annual geo-referenced coca maps from the United Nations Office on Drugs and Crime (UNODC) with satellite-based night-time lights, household survey data, agricultural and prison census records, and municipal election outcomes. We find that coca exposure increases local economic activity, household income, consumption, and wages. At the same time, it raises household victimization and is associated with higher incarceration-linked crime, especially for drug-related and gang-related offenses. Cohort-based evidence further suggests that exposure to coca-producing environments during youth has persistent criminal consequences later in life. We find more limited evidence on political outcomes, though the results are consistent with coca being associated with changes in local political competition. Overall, our findings show that coca generates meaningful short-run local economic gains, but that these gains coexist with substantial social and criminal costs.
            </p>
          </details>
        </article>
        <article className="publication">
          <h3>Ideology and Corruption: Policies and People</h3>
          <p><a href="https://www.dropbox.com/scl/fi/gcen8mc7shlv95rjkowxz/L-pez-Villalba-Ruzzier_Ideology-and-Corruption_country-analysis.pdf?rlkey=5w8ui6lcjp03w6p4re14lg4tg&st=6keueo2k&dl=0">[Latest version]</a></p>
          <p className="meta">with <a href="https://sites.google.com/site/christianruzzier/home">Christian A. Ruzzier</a>.</p>
          <details className="abstract">
            <summary>Abstract</summary>
            <p>
              Corruption constitutes a major impediment to economic development. We contend that who sits at the controls matters for corruption, and explore the effects of electing a government of a certain ideology. We argue that electing such a government may change the policies pursued, as well as the people who implement them and the institutions that constrain them, and that the interaction of these changes helps explain the effect on corruption. Employing a regression-discontinuity design on a dataset of worldwide national general elections in the post-WWII period, we find a causal effect of electing a government with a left-wing ideology on overall corruption. On average, countries under left-wing governments experience more systemic corruption in the four years after the election—a 13.2% increase in the index compared to the mean of non-left governments. The effect materializes gradually over time and can be seen both in the bureaucracy (petty corruption) and in the executive, legislative, and judicial branches of the state (grand corruption). Our evidence suggests that the effect operates through both policies, and people and institutions: left-wing governments intervene more extensively in the economy, while also being associated with lower-quality bureaucracies and weaker constraints on government. These changes are concentrated in countries with weaker checks and balances and, given the complementarity between these dimensions, can amplify corruption.
            </p>
          </details>
        </article>
      </section>
      <section className="research-section" aria-labelledby="work-in-progress">
        <h2 id="work-in-progress">Work in Progress</h2>
        <article className="publication">
          <h3>Household Insurance after Formal Job Loss in a High-Informality Setting</h3>
          <details className="abstract">
            <summary>Abstract</summary>
            <p>
              This project studies how households adjust to formal job loss in Ecuador by combining longitudinal employment surveys with administrative employer-employee records. The survey data allow me to follow workers and their household members across formal employment, informal employment, unemployment, and nonparticipation, while the administrative records provide detailed information on formal workers and their employers. To address the endogeneity of job separations, I exploit idiosyncratic firm-level employment contractions as an instrument for formal job loss. I examine how the loss of a formal job affects the labor supply of other household members and whether informal employment provides a margin through which households insure against the resulting income shock.
            </p>
          </details>
        </article>
      </section>
      <section className="research-section" aria-labelledby="publications">
        <h2 id="publications">Publications</h2>
        <article className="publication">
          <h3>
            <a href="https://direct.mit.edu/rest/article/104/1/133/97646/The-Long-Term-Effect-of-Military-Conscription-on">
              The Long-Term Effect of Military Conscription on Personality and Beliefs
            </a>
          </h3>
          <p className="meta">
            with <a href="https://sites.google.com/udesa.edu.ar/gabrielaertolanavajas/home">Gabriela Ertola Navajas</a>,{" "}
            <a href="https://www.antoniavazquez.com">Antonia Vazquez</a> and{" "}
            <a href="https://sites.google.com/a/udesa.edu.ar/mrossi/">Martín A. Rossi</a>.
          </p>
          <p><strong><em>The Review of Economics and Statistics</em></strong>, 104(1), 2022.</p>
          <details className="abstract">
            <summary>Abstract</summary>
            <p>
              We estimate the causal impact of military conscription on long-term beliefs and personality traits. To address potential endogeneity concerns, we exploit the conscription lottery in Argentina. We combine administrative data from the conscription lottery with data from a survey we designed on beliefs and personality traits. We find that men who were conscripted are more likely to adopt a military mind-set and that the effect is long lasting. Given the many people who go through military conscription, our results are useful for understanding how personality traits and beliefs are formed for a very salient part of the world&apos;s population.
            </p>
          </details>
        </article>
        <article className="publication">
          <h3>
            <a href="https://www.sciencedirect.com/science/article/abs/pii/S1090944320300697">
              Firm-level productivity in Latin America and the Caribbean
            </a>
          </h3>
          <p className="meta">with <a href="https://idbinvest.org/en/blog/author/lucas-figal-garone">Lucas Figal Garone</a>, <a href="https://idbinvest.org/en/member/alessandro-maffioli">Alessandro Maffioli</a> and <a href="https://sites.google.com/site/christianruzzier/home">Christian A. Ruzzier</a>.</p>
          <p><strong><em>Research in Economics</em></strong>, 74(2), 2020.</p>
          <details className="abstract">
            <summary>Abstract</summary>
            <p>
              While the accumulation of factors of production, both physical and <a href="https://www.sciencedirect.com/topics/economics-econometrics-and-finance/human-capital">human capital</a>, has helped Latin America and the Caribbean (LAC) to narrow the income gap with developed economies, aggregate productivity is still relatively low. Although there are numerous determinants of aggregate productivity, it is largely based on the underlying productivity of all firms in the economy. Using firm-level data from several waves of the World Bank Enterprise Survey and Chile&apos;s National Manufacturing Survey, we explore the <em>‘what’</em> question on productivity dispersion in LAC. We document three stylized facts: (i) there are significant differences in firm productivity within <a href="https://www.sciencedirect.com/topics/economics-econometrics-and-finance/industry">industries</a> – the firm at the 90th percentile of the productivity distribution produces almost seven times as much output (using the same measured inputs) as the 10th percentile firm; (ii) productivity differences persist over time – regressing a firm&apos;s current productivity on its one-year lagged productivity yields an autoregressive coefficient of around 0.9; and (iii) most of the growth in aggregate productivity comes from improvements in the productivity of existing firms.
            </p>
          </details>
        </article>
      </section>
      </div>
      </div>
    </main>
  );
}
